- name: 'Create group'
  group:
    name: deploy
    state: present

- name: 'Create user'
  user:
    name: '{{ deploy_user }}'
    shell: /bin/bash
    groups: sudo
    append: yes
    state: present

- name: 'Add SSH key for deploy user from variable'
  ansible.builtin.authorized_key:
    user: "deploy"
    state: present
    key: "{{ deploy_ssh_public_key }}"
