[db_servers]
server1 ansible_host=192.168.64.7

[webservers]
server1 ansible_host=192.168.64.7

[webservers:vars]
ansible_user=keit 
ansible_ssh_private_key_file=/Users/enadolinskaia/.ssh/id_ed25519

[db_servers:vars]
ansible_user=keit 
ansible_ssh_private_key_file=/Users/enadolinskaia/.ssh/id_ed25519
ansible_ssh_common_args='-o ControlMaster=no -o ControlPersist=no -o ControlPath=none'
