- name: 'Deploy app'
  hosts: webservers
  vars_files:
    - vars/app.yml 
  become: yes

  tasks:
    - name: 'Copy app files'
      template:
        src: index.html.j2
        dest: '{{ app_directory }}/index.html'
        owner: appuser
        mode: '0644'
      notify: Reload nginx

  handlers:
    - name: 'Reload nginx'
      service:
        name: nginx
        state: reloaded
